import { notFound } from "next/navigation";
import { readDB } from "@/lib/store";
import { isAddonEnabled } from "@/lib/addons";
import { TopBar } from "@/components/topbar";
import { WeeklyReviewView } from "@/components/fitness/weekly-review-view";

// The Weekly Review surface — the analysis vertical of the Fitness add-on. A server
// component (mirrors the Nutrition Food Log page) that GATES the route on the add-on flag
// and renders the page shell, then hands off to the interactive client view. Reviews are
// generated by an external agent (e.g. Claude Cowork via the fitness MCP) over the health +
// nutrition data and read back here as a history feed.
//
// GATED: when the "fitness" add-on is disabled this 404s (notFound), so a hand-typed
// /fitness/weekly-review has no reachable surface even though the underlying data stays on
// disk + readable via the API (the nav group hides when disabled, the WRITE routes gate
// server-side — the surface must 404 too so the disabled add-on is fully dormant).
export const dynamic = "force-dynamic";

export default async function WeeklyReviewPage() {
  const db = await readDB();
  if (!isAddonEnabled(db, "fitness")) notFound();

  return (
    <>
      <TopBar crumbs={["Cos", "Fitness", "Weekly review"]} live />
      <WeeklyReviewView />
    </>
  );
}
