import { notFound } from "next/navigation";
import { readDB } from "@/lib/store";
import { isAddonEnabled } from "@/lib/addons";
import { TopBar } from "@/components/topbar";
import { TrainingPlanView } from "@/components/fitness/training-plan-view";

// The Training Plan surface — a vertical of the Fitness add-on. A server component (like
// the Nutrition Food Log page) that renders the page shell + the interactive client view.
// Plans are generated by an external agent (e.g. Claude Cowork via the fitness MCP) and read
// back here as a history feed, but the surface is an OPTIONAL add-on: this page is GATED —
// when the "fitness" add-on is disabled
// it 404s (notFound), so a disabled add-on has no reachable surface even though its routes
// stay on disk.
export const dynamic = "force-dynamic";

export default async function TrainingPlanPage() {
  const db = await readDB();
  // Gate the surface on the add-on flag. The WRITE routes gate server-side (a disabled
  // add-on refuses the calendar push), and the nav group hides when disabled — but a
  // hand-typed /fitness/training-plan must also 404, so the disabled add-on is fully dormant.
  if (!isAddonEnabled(db, "fitness")) notFound();

  return (
    <>
      <TopBar crumbs={["Cos", "Fitness", "Training plan"]} live />
      <TrainingPlanView />
    </>
  );
}
