import { notFound } from "next/navigation";
import { readDB } from "@/lib/store";
import { isAddonEnabled } from "@/lib/addons";
import { TopBar } from "@/components/topbar";
import { PreWorkoutBriefView } from "@/components/fitness/pre-workout-brief-view";

// The Pre-workout Brief surface — the readiness vertical of the Fitness add-on. A server
// component (mirrors the Training Plan / Weekly Review pages) that GATES the route on the
// add-on flag and renders the page shell, then hands off to the interactive client view.
// Briefs are generated by an external agent (e.g. Claude Cowork via the fitness MCP) over the
// recent health data + the daily form score and read back here as a history feed.
//
// GATED: when the "fitness" add-on is disabled this 404s (notFound), so a hand-typed
// /fitness/pre-workout-brief has no reachable surface even though the underlying data stays
// on disk + readable via the API (the nav group hides when disabled, the WRITE routes gate
// server-side — the surface must 404 too so the disabled add-on is fully dormant).
export const dynamic = "force-dynamic";

export default async function PreWorkoutBriefPage() {
  const db = await readDB();
  // Gate the surface on the add-on flag. The WRITE routes gate server-side, and the nav
  // group hides when disabled — but a hand-typed /fitness/pre-workout-brief must also 404,
  // so the disabled add-on is fully dormant.
  if (!isAddonEnabled(db, "fitness")) notFound();

  return (
    <>
      <TopBar crumbs={["Cos", "Fitness", "Pre-workout brief"]} live />
      <PreWorkoutBriefView />
    </>
  );
}
