"use client";

// The Pre-workout Brief surface — the readiness vertical of the Fitness add-on. A READ-ONLY
// history feed: each brief is persisted (one per calendar day) on db.coachingArtifacts and
// navigable as history. Briefs are GENERATED by an external agent (e.g. Claude Cowork via the
// fitness MCP's save_pre_workout_brief tool / POST /api/fitness/coaching) — the board itself
// never calls an LLM — and the shared <ArtifactFeed> refetches the kind="pre_workout_brief"
// history over SSE, rendering the newest by default with a page-back rail. This view owns only
// the per-item presentation (readiness banner + form score, recommended session, watch-outs /
// green-lights) — the feed is the single source of truth for the artifact data.

import { IconWarning, IconCheckCircle } from "@/components/icons";
import { ArtifactFeed } from "@/components/fitness/artifact-feed";

interface RecommendedSession {
  sport: string;
  duration_min: number;
  intensity: string;
  description: string;
}

interface Brief {
  readiness: string;
  form_score: number;
  recommended_session: RecommendedSession;
  warnings: string[];
  green_lights: string[];
  one_liner: string;
}

// Keyed on the English readiness vocabulary the agent-generated brief carries
// ("ready" | "caution" | "rest"). The fallback (READINESS_STYLE.caution) keeps the
// banner sane if the route ever returns an unmapped value. "rest" is the danger tone, so it
// uses rose-* (NOT red-* — red is the LabelColor token, not a semantic tone).
const READINESS_STYLE: Record<string, { bg: string; border: string; text: string; badge: string }> = {
  ready: {
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    text: "text-emerald-800",
    badge: "bg-emerald-100 text-emerald-700 border-emerald-300",
  },
  caution: {
    bg: "bg-amber-50",
    border: "border-amber-200",
    text: "text-amber-800",
    badge: "bg-amber-100 text-amber-700 border-amber-300",
  },
  rest: {
    bg: "bg-rose-50",
    border: "border-rose-200",
    text: "text-rose-800",
    badge: "bg-rose-100 text-rose-700 border-rose-300",
  },
};

// Human label for a readiness value (the route returns the canonical English key; this
// renders it as a display chip).
const READINESS_LABEL: Record<string, string> = {
  ready: "Ready",
  caution: "Caution",
  rest: "Rest recommended",
};

function scoreColor(s: number): string {
  if (s >= 75) return "text-emerald-600";
  if (s >= 50) return "text-amber-600";
  return "text-rose-600";
}

function scoreRing(s: number): string {
  if (s >= 75) return "border-emerald-300 bg-emerald-50";
  if (s >= 50) return "border-amber-300 bg-amber-50";
  return "border-rose-300 bg-rose-50";
}

// Keyed on the English intensity vocabulary ("easy" | "moderate" | "hard"). "hard" is not a
// danger tone — it stays amber (an exertion cue), reserving rose for the rest/error state.
const INTENSITY_BADGE: Record<string, string> = {
  easy: "bg-emerald-50 text-emerald-700 border-emerald-200",
  moderate: "bg-amber-50 text-amber-700 border-amber-200",
  hard: "bg-amber-50 text-amber-700 border-amber-200",
};

const INTENSITY_LABEL: Record<string, string> = {
  easy: "Easy",
  moderate: "Moderate",
  hard: "Hard",
};

// Render one persisted brief from its stored payload (the verbatim route output). The feed
// supplies (payload, artifact); we only read the brief fields off payload.
function renderBrief(payload: Record<string, unknown>) {
  const brief = payload as unknown as Brief;
  const style = READINESS_STYLE[brief.readiness] ?? READINESS_STYLE.caution;
  const session = brief.recommended_session ?? ({} as RecommendedSession);
  const warnings = Array.isArray(brief.warnings) ? brief.warnings : [];
  const greenLights = Array.isArray(brief.green_lights) ? brief.green_lights : [];

  return (
    <div className="space-y-6">
      {/* Readiness banner + score */}
      <div className={`rounded-lg border ${style.border} ${style.bg} px-5 py-4`}>
        <div className="flex gap-4 items-center">
          <div
            className={`w-16 h-16 shrink-0 rounded-2xl border-2 flex flex-col items-center justify-center ${scoreRing(brief.form_score)}`}
          >
            <span className={`text-[24px] font-bold leading-none tabular-nums ${scoreColor(brief.form_score)}`}>
              {brief.form_score}
            </span>
            <span className="text-[9px] font-medium text-ink-400 mt-0.5">/ 100</span>
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <span className={`text-[12px] font-semibold px-2.5 py-0.5 rounded-full border ${style.badge}`}>
                {READINESS_LABEL[brief.readiness] ?? brief.readiness}
              </span>
            </div>
            <p className={`text-[14px] font-medium ${style.text} leading-relaxed`}>
              {brief.one_liner}
            </p>
          </div>
        </div>
      </div>

      {/* Recommended session */}
      <div className="rounded-lg border border-ink-100 bg-white px-5 py-4 shadow-card">
        <p className="text-[11px] font-medium uppercase tracking-wider text-ink-400 mb-3">
          Recommended session
        </p>
        <div className="flex items-center gap-3 mb-2">
          <span className="text-[14px] font-semibold text-ink-900">
            {session.sport}
          </span>
          <span className={`text-[11px] font-medium px-2 py-0.5 rounded-full border ${INTENSITY_BADGE[session.intensity] ?? "bg-ink-50 text-ink-600 border-ink-200"}`}>
            {INTENSITY_LABEL[session.intensity] ?? session.intensity}
          </span>
          <span className="text-[12px] text-ink-500 tabular-nums">
            {session.duration_min} min
          </span>
        </div>
        <p className="text-[12px] text-ink-600 leading-relaxed">
          {session.description}
        </p>
      </div>

      {/* Warnings + Green lights */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {warnings.length > 0 && (
          <div className="rounded-lg border border-amber-200 bg-amber-50 px-5 py-4">
            <p className="text-[11px] font-medium uppercase tracking-wider text-amber-500 mb-2">
              Watch-outs
            </p>
            <ul className="space-y-1">
              {warnings.map((w, i) => (
                <li key={i} className="text-[12px] text-amber-800 flex gap-1.5">
                  <IconWarning className="w-3.5 h-3.5 mt-px shrink-0 text-amber-500" /> {w}
                </li>
              ))}
            </ul>
          </div>
        )}
        {greenLights.length > 0 && (
          <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-5 py-4">
            <p className="text-[11px] font-medium uppercase tracking-wider text-emerald-500 mb-2">
              Green lights
            </p>
            <ul className="space-y-1">
              {greenLights.map((g, i) => (
                <li key={i} className="text-[12px] text-emerald-800 flex gap-1.5">
                  <IconCheckCircle className="w-3.5 h-3.5 mt-px shrink-0 text-emerald-500" /> {g}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}

export function PreWorkoutBriefView() {
  return (
    <ArtifactFeed
      kind="pre_workout_brief"
      title="Pre-workout brief"
      emptyHint="No pre-workout briefs yet. Ask your Cos agent (e.g. in Claude Cowork: “should I train today?”) to analyze your form — your readiness brief will appear here automatically."
      renderItem={renderBrief}
    />
  );
}
