"use client";

// The Training Plan surface — a READ-ONLY history feed over the Fitness add-on's persisted
// coaching artifacts (db.coachingArtifacts, kind "training_plan"). The shared <ArtifactFeed>
// owns all data: it lists the persisted plans newest-first, renders the history rail +
// prev/next steppers, and re-fetches over SSE. Plans are GENERATED by an external agent (e.g.
// Claude Cowork via the fitness MCP's save_training_plan tool / POST /api/fitness/coaching) —
// the board itself never calls an LLM — and appear here automatically. This view supplies only
// the per-item presentation (renderItem, reading from the artifact payload). A viewed plan's
// sessions can still be pushed to the calendar (POST /api/fitness/push-plan-to-calendar via the
// shared fitness-client).

import { useState } from "react";
import { pushPlanToCalendar } from "@/lib/fitness-client";
import { formatDay } from "@/lib/fitness-format";
import { IconRunner, IconHeart, IconCheck } from "@/components/icons";
import { Markdown } from "@/components/shared/markdown";
import { ArtifactFeed } from "@/components/fitness/artifact-feed";

// ── Types ────────────────────────────────────────────────────────────────────

interface PlanDay {
  date: string;
  day: string;
  type: string;
  sport: string;
  duration_min: number;
  intensity: string;
  description: string;
  zones: string;
}

interface TrainingPlan {
  week: string;
  generated_at: string;
  recovery_status: string;
  days: PlanDay[];
  weekly_notes: string;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

// Keyed on the English intensity vocabulary the agent-generated plan carries
// ("easy" | "moderate" | "hard").
const INTENSITY_COLORS: Record<string, string> = {
  easy: "bg-emerald-50 text-emerald-700 border-emerald-200",
  moderate: "bg-amber-50 text-amber-700 border-amber-200",
  hard: "bg-rose-50 text-rose-700 border-rose-200",
};

const INTENSITY_LABEL: Record<string, string> = {
  easy: "Easy",
  moderate: "Moderate",
  hard: "Hard",
};

const RECOVERY_BADGE: Record<string, { label: string; cls: string }> = {
  good: { label: "Good recovery", cls: "bg-emerald-50 text-emerald-700 border-emerald-200" },
  moderate: { label: "Moderate recovery", cls: "bg-amber-50 text-amber-700 border-amber-200" },
  poor: { label: "Poor recovery", cls: "bg-rose-50 text-rose-700 border-rose-200" },
};

// The day-type glyph, keyed on the English day-type vocabulary
// ("training" | "rest" | "active_recovery"). Shared Icon* components (never hand-rolled
// SVGs); a rest day is a quiet muted dot. Unknown types fall back to the training runner.
function TypeIcon({ type }: { type: string }) {
  switch (type) {
    case "rest":
      return <IconCheck className="w-3.5 h-3.5 text-ink-400" />;
    case "active_recovery":
      return <IconHeart className="w-3.5 h-3.5 text-ink-400" />;
    case "training":
    default:
      return <IconRunner className="w-3.5 h-3.5 text-ink-400" />;
  }
}

// ── View ─────────────────────────────────────────────────────────────────────

export function TrainingPlanView() {
  return (
    <ArtifactFeed
      kind="training_plan"
      title="Training plan"
      emptyHint="No training plans yet. Ask your Cos agent (e.g. in Claude Cowork: “make me a training plan”) to generate one — it'll appear here automatically."
      renderItem={(payload) => <PlanBody plan={payload as unknown as TrainingPlan} />}
    />
  );
}

// The rendered plan body — the EXACT presentational JSX from the original view, now reading
// from the persisted artifact payload instead of an on-demand useState. Owns the calendar
// push (the one mutation a viewed plan still drives).
function PlanBody({ plan }: { plan: TrainingPlan }) {
  const [pushing, setPushing] = useState(false);
  const [pushResult, setPushResult] = useState<{ created: number; failed: number } | null>(null);
  const [error, setError] = useState<string | null>(null);

  const days = Array.isArray(plan.days) ? plan.days : [];

  // Push the plan's sessions to the calendar via the shared fitness-client (which throws
  // Error(<api error text>) on a non-2xx). On a throw we surface the message in the rose error
  // banner; the double-submit guard is the `pushing` disabled state on the button.
  const pushToCalendar = async () => {
    setPushing(true);
    setPushResult(null);
    setError(null);
    try {
      const data = await pushPlanToCalendar({ days: days as unknown as Record<string, unknown>[] });
      setPushResult({ created: data.created, failed: data.failed });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Calendar error");
    } finally {
      setPushing(false);
    }
  };

  const totalMin = days.reduce((s, d) => s + (d.duration_min || 0), 0);
  const trainingDays = days.filter((d) => d.type === "training").length;

  return (
    <div className="space-y-6">
      {/* Calendar push action */}
      <div className="flex items-center justify-end">
        <button
          onClick={pushToCalendar}
          disabled={pushing}
          className="px-4 py-1.5 rounded-md border border-ink-200 bg-white text-ink-700 text-[13px] font-medium hover:bg-ink-50 disabled:opacity-50 transition"
        >
          {pushing ? "Adding…" : "Add to calendar"}
        </button>
      </div>

      {/* Push result */}
      {pushResult && (
        <div className={`rounded-lg border px-4 py-3 ${pushResult.failed === 0 ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}>
          <p className={`text-[13px] ${pushResult.failed === 0 ? "text-emerald-700" : "text-amber-700"}`}>
            {pushResult.created} event{pushResult.created === 1 ? "" : "s"} added to the calendar
            {pushResult.failed > 0 && ` (${pushResult.failed} failed)`}
          </p>
        </div>
      )}

      {/* Error — danger tone is rose, role="alert" so it's announced. */}
      {error && (
        <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3">
          <p className="text-[13px] text-rose-700">{error}</p>
        </div>
      )}

      {/* Summary cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <SummaryCard label="Week" value={plan.week} />
        <SummaryCard label="Sessions" value={`${trainingDays} days`} />
        <SummaryCard label="Total volume" value={`${Math.round(totalMin / 60 * 10) / 10}h`} />
        <div className="rounded-lg border border-ink-100 bg-white px-4 py-3 shadow-card">
          <p className="text-[11px] font-medium uppercase tracking-wider text-ink-400">
            Recovery
          </p>
          <p className="mt-1">
            <span
              className={`inline-block text-[12px] font-medium px-2 py-0.5 rounded-full border ${
                RECOVERY_BADGE[plan.recovery_status]?.cls ?? "bg-ink-50 text-ink-600 border-ink-200"
              }`}
            >
              {RECOVERY_BADGE[plan.recovery_status]?.label ?? plan.recovery_status}
            </span>
          </p>
        </div>
      </div>

      {/* Day-by-day plan */}
      <div className="rounded-lg border border-ink-100 bg-white shadow-card overflow-hidden">
        <div className="divide-y divide-ink-100">
          {days.map((day) => (
            <div key={day.date} className="px-5 py-4">
              <div className="flex items-start gap-4">
                {/* Date column */}
                <div className="w-20 shrink-0">
                  <p className="text-[13px] font-semibold text-ink-900">
                    {day.day}
                  </p>
                  <p className="text-[11px] text-ink-400">
                    {formatDay(day.date)}
                  </p>
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <TypeIcon type={day.type} />
                    <span className="text-[13px] font-medium text-ink-900">
                      {day.sport}
                    </span>
                    {day.type !== "rest" && (
                      <>
                        <span
                          className={`text-[11px] font-medium px-1.5 py-0.5 rounded border ${
                            INTENSITY_COLORS[day.intensity] ?? "bg-ink-50 text-ink-600 border-ink-200"
                          }`}
                        >
                          {INTENSITY_LABEL[day.intensity] ?? day.intensity}
                        </span>
                        {day.duration_min > 0 && (
                          <span className="text-[12px] text-ink-500 tabular-nums">
                            {day.duration_min} min
                          </span>
                        )}
                      </>
                    )}
                  </div>
                  {day.description && (
                    <p className="mt-1 text-[12px] text-ink-600 leading-relaxed">
                      {day.description}
                    </p>
                  )}
                  {day.zones && day.type !== "rest" && (
                    <p className="mt-0.5 text-[11px] text-ink-400">
                      Zones: {day.zones}
                    </p>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Weekly notes */}
      {plan.weekly_notes && (
        <div className="rounded-lg border border-ink-100 bg-white px-5 py-4 shadow-card">
          <p className="text-[11px] font-medium uppercase tracking-wider text-ink-400 mb-1">
            Weekly notes
          </p>
          <Markdown className="text-[13px] text-ink-700">{plan.weekly_notes}</Markdown>
        </div>
      )}
    </div>
  );
}

function SummaryCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-ink-100 bg-white px-4 py-3 shadow-card">
      <p className="text-[11px] font-medium uppercase tracking-wider text-ink-400">
        {label}
      </p>
      <p className="mt-1 text-[20px] font-semibold text-ink-900 tabular-nums leading-tight">
        {value}
      </p>
    </div>
  );
}
