"use client";

// The Weekly Review surface — a READ-ONLY history feed over the Fitness add-on's persisted
// coaching artifacts (db.coachingArtifacts, kind "weekly_review"). The shared <ArtifactFeed>
// owns all data: it lists the persisted reviews newest-first, renders the history rail +
// prev/next steppers, and re-fetches over SSE. This view supplies only the per-item
// presentation (renderItem, reading from the artifact payload).
//
// Reviews are GENERATED by an external agent (e.g. Claude Cowork via the fitness MCP's
// save_weekly_review tool / POST /api/fitness/coaching) — the board itself never calls an LLM.
// The agent analyses the health + nutrition data, augments the review with avg_form_score +
// form_trend, and persists it; over SSE the new review appears here automatically.

import { ArtifactFeed } from "@/components/fitness/artifact-feed";

// ── Types ────────────────────────────────────────────────────────────────────

interface TrainingBlock {
  sessions_done: number;
  total_volume_min: number;
  total_distance_km: number;
  sports_breakdown: Record<string, number>;
  vs_plan: string;
  highlights: string[];
}

interface SleepBlock {
  avg_duration_h: number;
  avg_deep_h: number;
  avg_rem_h: number;
  quality_trend: string;
  notes: string;
}

interface RecoveryBlock {
  avg_hrv: number;
  avg_resting_hr: number;
  fatigue_level: string;
  notes: string;
}

interface NutritionBlock {
  days_logged: number;
  avg_calories: number;
  notes: string;
}

interface WeeklyReview {
  week: string;
  generated_at: string;
  overall_score: number;
  summary: string;
  training: TrainingBlock;
  sleep: SleepBlock;
  recovery: RecoveryBlock;
  nutrition: NutritionBlock;
  recommendations: string[];
  next_week_focus: string;
  avg_form_score: number | null;
  form_trend: string | null;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function scoreColor(score: number): string {
  if (score >= 75) return "text-emerald-600";
  if (score >= 50) return "text-amber-600";
  return "text-rose-600";
}

function scoreRing(score: number): string {
  if (score >= 75) return "border-emerald-300 bg-emerald-50";
  if (score >= 50) return "border-amber-300 bg-amber-50";
  return "border-rose-300 bg-rose-50";
}

// Keyed on the English fatigue vocabulary the agent-generated review carries
// ("low" | "moderate" | "high").
const FATIGUE_BADGE: Record<string, string> = {
  low: "bg-emerald-50 text-emerald-700 border-emerald-200",
  moderate: "bg-amber-50 text-amber-700 border-amber-200",
  high: "bg-rose-50 text-rose-700 border-rose-200",
};

const FATIGUE_LABEL: Record<string, string> = {
  low: "Low",
  moderate: "Moderate",
  high: "High",
};

// Keyed on the English trend vocabulary ("improving" | "stable" | "declining"), shared by
// sleep.quality_trend and form_trend.
const TREND_BADGE: Record<string, string> = {
  improving: "bg-emerald-50 text-emerald-700 border-emerald-200",
  stable: "bg-ink-50 text-ink-600 border-ink-200",
  declining: "bg-rose-50 text-rose-700 border-rose-200",
};

const TREND_LABEL: Record<string, string> = {
  improving: "Improving",
  stable: "Stable",
  declining: "Declining",
};

function fmtH(n: number | undefined | null): string {
  if (n == null || !Number.isFinite(n)) return "--";
  return `${n.toFixed(1)}h`;
}

function fmtNum(n: number | undefined | null): string {
  if (n == null || !Number.isFinite(n)) return "--";
  return n % 1 === 0 ? String(n) : n.toFixed(1);
}

// ── View ─────────────────────────────────────────────────────────────────────

export function WeeklyReviewView() {
  return (
    <ArtifactFeed
      kind="weekly_review"
      title="Weekly review"
      emptyHint="No weekly reviews yet. Ask your Cos agent (e.g. in Claude Cowork: “how was my training this week?”) to run a weekly review — it'll appear here automatically."
      renderItem={(payload) => <ReviewBody review={payload as unknown as WeeklyReview} />}
    />
  );
}

// The rendered review body — the EXACT presentational JSX from the original view, now reading
// from the persisted artifact payload instead of an on-demand useState.
function ReviewBody({ review }: { review: WeeklyReview }) {
  const training = review.training ?? ({} as TrainingBlock);
  const sleep = review.sleep ?? ({} as SleepBlock);
  const recovery = review.recovery ?? ({} as RecoveryBlock);
  const nutrition = review.nutrition ?? ({} as NutritionBlock);
  const sportsBreakdown = training.sports_breakdown ?? {};
  const highlights = training.highlights ?? [];
  const recommendations = review.recommendations ?? [];

  return (
    <div className="space-y-6">
      {/* Score + Summary */}
      <div className="flex gap-4 items-start">
        <div
          className={`w-24 h-24 shrink-0 rounded-2xl border-2 flex flex-col items-center justify-center ${scoreRing(review.overall_score)}`}
        >
          <span className={`text-[32px] font-bold leading-none tabular-nums ${scoreColor(review.overall_score)}`}>
            {review.overall_score}
          </span>
          <span className="text-[10px] font-medium text-ink-400 mt-0.5">/ 100</span>
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-[11px] font-medium uppercase tracking-wider text-ink-400">
            {review.week}
          </p>
          <p className="mt-1 text-[14px] text-ink-800 leading-relaxed">
            {review.summary}
          </p>
        </div>
      </div>

      {/* Grid: Training + Sleep */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Training */}
        <Section title="Training">
          <div className="grid grid-cols-3 gap-3 mb-3">
            <MiniCard label="Sessions" value={String(training.sessions_done)} />
            <MiniCard
              label="Volume"
              value={`${Math.round(training.total_volume_min / 60 * 10) / 10}h`}
            />
            <MiniCard
              label="Distance"
              value={`${fmtNum(training.total_distance_km)} km`}
            />
          </div>
          {Object.keys(sportsBreakdown).length > 0 && (
            <div className="mb-3">
              <p className="text-[11px] font-medium text-ink-400 mb-1">Breakdown</p>
              <div className="flex flex-wrap gap-2">
                {Object.entries(sportsBreakdown).map(([sport, min]) => (
                  <span
                    key={sport}
                    className="text-[12px] px-2 py-0.5 rounded-full bg-ink-50 text-ink-700 border border-ink-100"
                  >
                    {sport}: {min} min
                  </span>
                ))}
              </div>
            </div>
          )}
          <p className="text-[12px] text-ink-600">{training.vs_plan}</p>
          {highlights.length > 0 && (
            <ul className="mt-2 space-y-0.5">
              {highlights.map((h, i) => (
                <li key={i} className="text-[12px] text-ink-600 flex gap-1.5">
                  <span className="text-emerald-500 shrink-0">+</span> {h}
                </li>
              ))}
            </ul>
          )}
        </Section>

        {/* Sleep */}
        <Section title="Sleep">
          <div className="grid grid-cols-3 gap-3 mb-3">
            <MiniCard label="Avg duration" value={fmtH(sleep.avg_duration_h)} />
            <MiniCard label="Deep" value={fmtH(sleep.avg_deep_h)} />
            <MiniCard label="REM" value={fmtH(sleep.avg_rem_h)} />
          </div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-[11px] font-medium text-ink-400">Trend:</span>
            <Badge
              label={TREND_LABEL[sleep.quality_trend] ?? sleep.quality_trend}
              cls={TREND_BADGE[sleep.quality_trend] ?? "bg-ink-50 text-ink-600 border-ink-200"}
            />
          </div>
          {sleep.notes && (
            <p className="text-[12px] text-ink-600">{sleep.notes}</p>
          )}
        </Section>
      </div>

      {/* Grid: Recovery + Nutrition */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Recovery */}
        <Section title="Recovery">
          <div className="grid grid-cols-2 gap-3 mb-3">
            <MiniCard label="Avg HRV" value={`${fmtNum(recovery.avg_hrv)} ms`} />
            <MiniCard label="Resting HR" value={`${fmtNum(recovery.avg_resting_hr)} bpm`} />
          </div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-[11px] font-medium text-ink-400">Fatigue:</span>
            <Badge
              label={FATIGUE_LABEL[recovery.fatigue_level] ?? recovery.fatigue_level}
              cls={FATIGUE_BADGE[recovery.fatigue_level] ?? "bg-ink-50 text-ink-600 border-ink-200"}
            />
          </div>
          {recovery.notes && (
            <p className="text-[12px] text-ink-600">{recovery.notes}</p>
          )}
        </Section>

        {/* Nutrition */}
        <Section title="Nutrition">
          <div className="grid grid-cols-2 gap-3 mb-3">
            <MiniCard label="Days logged" value={String(nutrition.days_logged)} />
            <MiniCard label="Avg kcal" value={fmtNum(nutrition.avg_calories)} />
          </div>
          {nutrition.notes && (
            <p className="text-[12px] text-ink-600">{nutrition.notes}</p>
          )}
        </Section>
      </div>

      {/* Form Score */}
      {review.avg_form_score != null && (
        <Section title="Average form score">
          <div className="flex items-center gap-4">
            <div
              className={`w-16 h-16 shrink-0 rounded-2xl border-2 flex flex-col items-center justify-center ${scoreRing(review.avg_form_score)}`}
            >
              <span className={`text-[24px] font-bold leading-none tabular-nums ${scoreColor(review.avg_form_score)}`}>
                {review.avg_form_score}
              </span>
              <span className="text-[9px] font-medium text-ink-400 mt-0.5">/ 100</span>
            </div>
            <div>
              <p className="text-[12px] text-ink-600 mb-1">
                Average form score over the week
              </p>
              {review.form_trend && (
                <div className="flex items-center gap-2">
                  <span className="text-[11px] font-medium text-ink-400">Trend:</span>
                  <Badge
                    label={TREND_LABEL[review.form_trend] ?? review.form_trend}
                    cls={TREND_BADGE[review.form_trend] ?? "bg-ink-50 text-ink-600 border-ink-200"}
                  />
                </div>
              )}
            </div>
          </div>
        </Section>
      )}

      {/* Recommendations */}
      {recommendations.length > 0 && (
        <Section title="Recommendations">
          <ul className="space-y-1.5">
            {recommendations.map((r, i) => (
              <li key={i} className="flex gap-2 text-[13px] text-ink-700">
                <span className="shrink-0 w-5 h-5 rounded-full bg-violet-50 text-violet-600 text-[11px] font-semibold flex items-center justify-center border border-violet-200">
                  {i + 1}
                </span>
                <span className="pt-0.5">{r}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Next week focus */}
      {review.next_week_focus && (
        <div className="rounded-lg border border-violet-200 bg-violet-50 px-5 py-4">
          <p className="text-[11px] font-medium uppercase tracking-wider text-violet-500 mb-1">
            Next week focus
          </p>
          <p className="text-[13px] text-violet-800 leading-relaxed">
            {review.next_week_focus}
          </p>
        </div>
      )}
    </div>
  );
}

// ── Components ───────────────────────────────────────────────────────────────

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-ink-100 bg-white px-5 py-4 shadow-card">
      <p className="text-[11px] font-medium uppercase tracking-wider text-ink-400 mb-3">
        {title}
      </p>
      {children}
    </div>
  );
}

function MiniCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-ink-100 bg-ink-50/50 px-3 py-2">
      <p className="text-[10px] font-medium uppercase tracking-wider text-ink-400">{label}</p>
      <p className="text-[16px] font-semibold text-ink-900 tabular-nums leading-tight mt-0.5">
        {value}
      </p>
    </div>
  );
}

function Badge({ label, cls }: { label: string; cls: string }) {
  return (
    <span className={`text-[11px] font-medium px-2 py-0.5 rounded-full border ${cls}`}>
      {label}
    </span>
  );
}
